apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-webapp
  namespace: argocd
  annotations:
    # The image-list annotation maps an alias to the actual image used by the deployment.
    # Here "my-webapp" is an alias, and "opensourceops/my-webapp" is the actual image name.
    argocd-image-updater.argoproj.io/image-list: my-webapp=opensourceops/my-webapp

    # Update strategy: "latest" means Image Updater will attempt to pull the latest tag from the registry.
    # Other strategies include "semver" or "digest". Adjust as needed.
    argocd-image-updater.argoproj.io/my-webapp.update-strategy: semver

    # Method for writing back changes to the repository.
    # "git" means that Image Updater will commit the updated manifests back to your Git repo.
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: 'https://github.com/Ompragash/manifest-repo.git'
    targetRevision: main
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
